// controllers/mocktest_controller.dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class RecentTestItem {
  final String title;
  final String subtitle;
  final int messageCount;
  final String timeAgo;
  final Color iconColor;

  RecentTestItem({
    required this.title,
    required this.subtitle,
    required this.messageCount,
    required this.timeAgo,
    required this.iconColor,
  });
}

class Chapter {
  final String title;
  final String pages;
  final int topics;
  bool isSelected;

  Chapter({
    required this.title,
    required this.pages,
    required this.topics,
    this.isSelected = false,
  });
}

class Book {
  final String title;
  final String subtitle;
  final List<Chapter> chapters;
  bool isExpanded;
  bool isSelected;

  Book({
    required this.title,
    required this.subtitle,
    required this.chapters,
    this.isExpanded = false,
    this.isSelected = false,
  });
}

class MockTestController extends GetxController {
  // Recent Tests
  var recentTests = <RecentTestItem>[].obs;

  // Add inside MockTestController class
var selectedRecentTestIndex = (-1).obs; // -1 = none selected

  // AI Mock Test
  var aiMockTestTitle = "AI Generated Mock Test".obs;
  var aiMockTestSubtitle =
      "Smart questions generated by AI based on Mathematics curriculum and difficulty levels".obs;

  // NEW: AI Test selection state
  var isAiMockTestSelected = false.obs;

  // Books & Materials
  var books = <Book>[].obs;

  // FIXED: Only ONE getter — includes both chapters AND AI test
  bool get hasAnySelection =>
      isAiMockTestSelected.value ||
      books.any((book) => book.chapters.any((chapter) => chapter.isSelected));

  @override
  void onInit() {
    super.onInit();
    loadAllData();
  }

  void loadAllData() {
    recentTests.assignAll([
      RecentTestItem(
        title: "Mathematics Textbook - Chapter 1",
        subtitle: "\"Explain domain and range concepts\"",
        messageCount: 5,
        timeAgo: "2 hours ago",
        iconColor: Colors.white,
      ),
      RecentTestItem(
        title: "AI Generated Mock Test",
        subtitle: "\"Help with calculus derivatives\"",
        messageCount: 12,
        timeAgo: "Yesterday",
        iconColor: Colors.white,
      ),
    ]);

    books.assignAll([
      Book(
        title: "Mathematics Textbook",
        subtitle: "Class 12 NCERT • 4 chapters",
        isSelected: true,
        isExpanded: true,
        chapters: [
          Chapter(title: "Chapter 1: Sets and Functions", pages: "1-25", topics: 3, isSelected: false),
          Chapter(title: "Chapter 2: Relations & Functions", pages: "26-68", topics: 5, isSelected: true),
          Chapter(title: "Chapter 3: Trigonometry", pages: "121-180", topics: 6, isSelected: false),
          Chapter(title: "Chapter 4: Calculus", pages: "181-250", topics: 8, isSelected: false),
        ],
      ),
      Book(
        title: "Chemistry Lab Manual",
        subtitle: "Lab Experiments • 3 chapters",
        isSelected: false,
        isExpanded: false,
        chapters: [
          Chapter(title: "Basic Laboratory Techniques", pages: "1-15", topics: 4),
          Chapter(title: "Identification of Ions", pages: "16-40", topics: 8),
          Chapter(title: "Titration Experiments", pages: "41-60", topics: 5),
        ],
      ),
      Book(
        title: "Physics NCERT Part I",
        subtitle: "Class 12 • 8 chapters",
        isSelected: false,
        isExpanded: false,
        chapters: [
          Chapter(title: "Electric Charges and Fields", pages: "1-30", topics: 10),
          Chapter(title: "Electrostatic Potential and Capacitance", pages: "31-65", topics: 12),
          Chapter(title: "Current Electricity", pages: "66-105", topics: 15),
          Chapter(title: "Moving Charges and Magnetism", pages: "106-135", topics: 14),
          Chapter(title: "Magnetism and Matter", pages: "136-155", topics: 8),
          Chapter(title: "Electromagnetic Induction", pages: "156-185", topics: 12),
          Chapter(title: "Alternating Current", pages: "186-215", topics: 13),
          Chapter(title: "Electromagnetic Waves", pages: "216-230", topics: 7),
        ],
      ),
    ]);
  }

  // Toggle Book Selection
  void toggleBookSelection(Book book) {
    book.isSelected = !book.isSelected;
    for (var chapter in book.chapters) {
      chapter.isSelected = book.isSelected;
    }
    refreshBooks();
  }

  // Toggle Chapter Selection
  void toggleChapterSelection(Book book, Chapter chapter) {
    chapter.isSelected = !chapter.isSelected;

    book.isSelected = book.chapters.every((c) => c.isSelected);
    if (!book.chapters.any((c) => c.isSelected)) {
      book.isSelected = false;
    }
    refreshBooks();
  }

  // Toggle Expand/Collapse Book
  void toggleBookExpand(Book book) {
    book.isExpanded = !book.isExpanded;
    refreshBooks();
  }

  // Helper to refresh UI
  void refreshBooks() {
    books.refresh();
  }
}